NETWORK_MANAGEMENT_QUIZ = {
    "ch-network-management": {
        "title": "Network Management Quiz: FCAPS · SNMP · NetFlow · ACLs · Hardening",
        "questions": [
            {
                "id": "q1",
                "type": "multiple_choice",
                "question": "A switch port keeps going up and down. Which FCAPS bucket covers detecting and fixing this?",
                "options": [
                    "Configuration",
                    "Accounting",
                    "Fault",
                    "Performance",
                ],
                "answer": 2,
                "explanation": "Fault management covers detecting and fixing network outages and failures — including a flapping switch port. The fix (replacing a bad cable, checking the SFP) is a fault management action.",
            },
            {
                "id": "q2",
                "type": "multiple_choice",
                "question": "What is the main security difference between SNMPv2c and SNMPv3?",
                "options": [
                    "SNMPv3 polls faster",
                    "SNMPv2c only works on Cisco devices",
                    "SNMPv3 adds authentication and encryption; SNMPv2c sends everything in plain text",
                    "SNMPv3 uses a different port number",
                ],
                "answer": 2,
                "explanation": "SNMPv2c sends the community string (which acts as a password) and all data in plain text — readable to anyone on the wire. SNMPv3 adds SHA authentication and AES encryption, making it the only safe choice for production.",
            },
            {
                "id": "q3",
                "type": "multiple_choice",
                "question": "NetFlow captures traffic metadata. Which of these would NOT appear in a NetFlow record?",
                "options": [
                    "Source and destination IP addresses",
                    "Destination port",
                    "The actual payload content of the packets",
                    "Number of bytes transferred",
                ],
                "answer": 2,
                "explanation": "NetFlow records metadata only: who talked to who, ports, protocols, byte counts, duration. It does not capture the payload (packet content). That's why it can reveal anomalous patterns even in encrypted sessions.",
            },
            {
                "id": "q4",
                "type": "true_false",
                "question": "On Cisco IOS, 'enable password' and 'enable secret' provide the same level of security.",
                "answer": False,
                "explanation": "'enable secret' uses a strong hash (MD5+) and is not reversible. 'enable password' uses a weak, reversible encoding that Cisco tools can decode trivially. Always use 'enable secret'.",
            },
            {
                "id": "q5",
                "type": "multiple_choice",
                "question": "What does the implicit 'deny any' at the end of a Cisco ACL mean?",
                "options": [
                    "The last rule always permits traffic",
                    "Any traffic not explicitly permitted by a rule is silently dropped",
                    "The ACL only applies to inbound traffic",
                    "You must add 'deny any' manually or the ACL has no effect",
                ],
                "answer": 1,
                "explanation": "Every Cisco ACL ends with an invisible 'deny any' rule. If a packet doesn't match any of your explicit permit rules, it gets dropped silently. This is why 'show access-lists' hit counts are important — they reveal which rules are actually matching traffic.",
            },
            {
                "id": "q6",
                "type": "multiple_choice",
                "question": "What makes an automation script 'idempotent'?",
                "options": [
                    "It runs faster than manual configuration",
                    "It can run on multiple vendors without changes",
                    "Running it multiple times produces the same result as running it once",
                    "It backs up the config before making changes",
                ],
                "answer": 2,
                "explanation": "Idempotency means the outcome is the same regardless of how many times the script runs. The check-before-push pattern achieves this: if the line is already in the config, skip it — no duplicates, no side effects on re-runs.",
            },
            {
                "id": "q7",
                "type": "multiple_choice",
                "question": "IP SLA is best described as:",
                "options": [
                    "A traffic filtering mechanism similar to ACLs",
                    "A scheduled synthetic test (like automated pings) that measures performance proactively",
                    "A backup protocol that saves configs automatically",
                    "A version of SNMP designed for high-speed polling",
                ],
                "answer": 1,
                "explanation": "IP SLA runs scheduled synthetic tests (ICMP echo, UDP jitter, TCP connect) from the router itself. It measures latency, loss, and jitter on a schedule so you know about degradation before users report it.",
            },
            {
                "id": "q8",
                "type": "multiple_choice",
                "question": "For enterprise WiFi authentication, what replaces a single shared passphrase?",
                "options": [
                    "WPS (Wi-Fi Protected Setup)",
                    "Hiding the SSID broadcast",
                    "802.1X with a RADIUS server for per-user authentication",
                    "WEP with a longer key",
                ],
                "answer": 2,
                "explanation": "802.1X + RADIUS gives each user their own credentials. One compromised password only exposes that user's access, not the whole network. WPS is actually a security risk (8-digit PIN is brute-forceable). SSID hiding provides no real protection.",
            },
        ],
    },
}
