PYTHON_ALGORITHMS_QUIZ = {
    "ch-python-algorithms": {
        "title": "Python Algorithms & Security Scripting Quiz",
        "questions": [
            {
                "id": "q1",
                "type": "multiple_choice",
                "question": "What is the worst-case time complexity of linear search on a list of n items?",
                "options": [
                    "O(1)",
                    "O(log n)",
                    "O(n)",
                    "O(n²)",
                ],
                "answer": 2,
                "explanation": "Linear search checks every element in the worst case (the target is at the end or not present). That's O(n) — the time grows proportionally with list size.",
            },
            {
                "id": "q2",
                "type": "multiple_choice",
                "question": "Binary search requires the list to be sorted. Why?",
                "options": [
                    "Because it was designed for Cisco devices",
                    "Because it uses the midpoint to decide which half to eliminate — only valid when the data has a meaningful order",
                    "Because unsorted lists are slower to iterate",
                    "Because Python's sort() is needed to initialize the search index",
                ],
                "answer": 1,
                "explanation": "Binary search works by comparing the target to the middle element and discarding one half. This only works if the data is sorted — otherwise 'the target is less than the midpoint' tells you nothing about which half to search.",
            },
            {
                "id": "q3",
                "type": "true_false",
                "question": "Python's sorted() function implements Bubble Sort under the hood.",
                "answer": False,
                "explanation": "Python uses Timsort — a highly optimized hybrid of merge sort and insertion sort. It's O(n log n) average/worst and O(n) on nearly-sorted data. Bubble Sort is O(n²) and is only used for teaching.",
            },
            {
                "id": "q4",
                "type": "multiple_choice",
                "question": "You need to sort a list of 10,000 security alerts by CVSS score and you need stable sort (equal scores keep their original order). Which approach should you use?",
                "options": [
                    "Bubble Sort — simple and stable",
                    "Quick Sort — fastest in practice",
                    "sorted() with key=lambda a: a.cvss_score — Timsort is stable and O(n log n)",
                    "Binary Search — O(log n) is faster",
                ],
                "answer": 2,
                "explanation": "sorted() uses Timsort which is stable (equal items keep their order), O(n log n), and much faster than a hand-written sort. Binary Search is not a sorting algorithm — it searches already-sorted data.",
            },
            {
                "id": "q5",
                "type": "multiple_choice",
                "question": "In Python, what does subprocess.run(['sysctl', '-n', 'kernel.randomize_va_space'], capture_output=True, text=True) do?",
                "options": [
                    "Reads the file /proc/sys/kernel/randomize_va_space directly",
                    "Runs the sysctl command and captures its stdout as a Python string",
                    "Sets the kernel parameter to the value provided",
                    "Raises an error because sysctl is not a Python module",
                ],
                "answer": 1,
                "explanation": "subprocess.run() executes a shell command as a child process. capture_output=True captures stdout and stderr. text=True decodes bytes to str. The result is available in result.stdout — this is the Python equivalent of val=$(sysctl -n kernel.randomize_va_space) in bash.",
            },
            {
                "id": "q6",
                "type": "multiple_choice",
                "question": "What does oct(Path('/etc/shadow').stat().st_mode)[-3:] return?",
                "options": [
                    "The file's owner username",
                    "The file's size in bytes",
                    "The last three digits of the octal permission string, e.g. '640'",
                    "The file's modification timestamp",
                ],
                "answer": 2,
                "explanation": "Path.stat().st_mode returns the full mode integer (including file type bits). oct() converts it to octal string like '0o100640'. [-3:] slices the last three characters — the familiar unix permission digits (owner/group/other).",
            },
            {
                "id": "q7",
                "type": "multiple_choice",
                "question": "In the arc-sec-audit OOP structure, what is the role of the base Auditor class?",
                "options": [
                    "It implements each of the nine security checks directly",
                    "It holds shared state (counters) and helpers (ok/warn/fail/run) so each check module stays flat and focused",
                    "It connects to the network devices via SSH",
                    "It replaces the need for subprocess by reimplementing shell commands in Python",
                ],
                "answer": 1,
                "explanation": "The Auditor base class is a shared-state container: it tracks passed/warnings/failed counts and exposes ok(), warn(), fail(), and run() helpers. Each check module gets an instance, calls those helpers, and the counters accumulate across all checks — separation of concerns.",
            },
            {
                "id": "q8",
                "type": "multiple_choice",
                "question": "Merge Sort uses O(n) extra memory. Which algorithm is O(1) space (in-place) and still runs in O(n log n)?",
                "options": [
                    "Bubble Sort",
                    "Radix Sort",
                    "Heap Sort",
                    "Insertion Sort",
                ],
                "answer": 2,
                "explanation": "Heap Sort is O(n log n) in all cases and operates in-place (O(1) extra space) using a binary heap structure. Merge Sort needs O(n) for the temporary arrays during merge. Bubble and Insertion Sort are O(n²). Radix Sort is O(nk) space.",
            },
        ],
    },
}
